[package]
name = "tucdp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
arc-swap = "1.7.1"
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
