name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux targets
        if: matrix.os == 'ubuntu-latest'
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Install Windows targets
        if: matrix.os == 'windows-latest'
        run: rustup target add x86_64-pc-windows-msvc

      - name: Build for Linux
        if: matrix.os == 'ubuntu-latest'
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Build for Windows
        if: matrix.os == 'windows-latest'
        run: cargo build --release --target x86_64-pc-windows-msvc

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-release
          path: target/release/tucdp